[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = 'ezgb'
version = '0.1'
description = 'A standalone Python library for working with git-bug repositories'
readme = 'README.md'
requires-python = '>=3.9'
dependencies = ['pygit2']
license = 'GPL-2.0-or-later'
license-files = ['COPYING']
authors = [
    { name = 'Konstantin Ryabitsev', email = 'konstantin@linuxfoundation.org' }
]
classifiers = [
    'Development Status :: 3 - Alpha',
    'Environment :: Console',
    'Intended Audience :: Developers',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Software Development :: Bug Tracking',
    'Topic :: Software Development :: Version Control :: Git',
]

[dependency-groups]
dev = [
    "mypy",
    "pytest",
    "ruff",
]

[project.urls]
'Homepage' = 'https://git.kernel.org/pub/scm/utils/ezgb/ezgb.git/'
'Source' = 'https://git.kernel.org/pub/scm/utils/ezgb/ezgb.git'
'Community' = 'https://lore.kernel.org/tools'

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--tb=short"
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"

[tool.mypy]
strict = true

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
